### ISSUE TITLE
Not getting any response when this app runs locally on Tableau Desktop app or on webdataconnector simulator running locally

### ISSUE THREAD

**Issue by vinod77** [Nexysweb/tableau-wdc-react#18]
**Description:** I am running this app ([tableau-wdc-react](https://github.com/Nexysweb/tableau-wdc-react)) locally & I am also running 
[webdataconnector](https://github.com/tableau/webdataconnector) locally with simulator, here: http://localhost:8888/Simulator/index.html 
But when I enter this app's local url: http://localhost:3000/ in to the `Connector URL` and click on Fetch Table Data. I am not getting any data.

I also tried running http://localhost:300 on Tableau Desktop app's WebDataConnector simulator. It also doesn't works on `Tableau Desktop` app as well. 

**Note:** It works as expected, i get the response when i run it here:
https://tableau.github.io/webdataconnector/Simulator/ and add the url https://nexysweb.github.io/tableau-wdc-react/ in connector url

Please let me know how to make it work running on local WebDataConnector, simulator app & on Tableau desktop app

**Comment by johnb8005** [comment]
it is hard to help you since I do not know what your config looks like, however I would suggest running your local version of the connector on https://tableau.github.io/webdataconnector/Simulator/ and open the inspector to see what it is trying to fetch. That might point you in the right direction.

Also note, that this repo is a package if you want a boilerplate you are probably better off using https://github.com/Nexysweb/tableau-wdc-react-boilerplate (which uses this as a package)

**Comment by johnb8005** [comment]
<img width="682" alt="Screenshot 2022-02-10 at 18 36 23" src="https://user-images.githubusercontent.com/3129983/153464324-bc0dd210-f8aa-437c-be45-ae71dd0e8834.png">

**Comment by johnb8005** [comment]
@vinod77 I am going to close this since haven;t heard back from you
